### ISSUE TITLE
The image for the service you're trying to recreate has been removed

### ISSUE THREAD

**Issue by airdogvan** [szabodanika/microbin#103]
Complete log:

docker-compose up
Pulling paste (microbin-docker:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling paste (microbin-docker:)...
ERROR: pull access denied for microbin-docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Docker-compose:
version: '3.7'

services:

  paste:
    container_name: microbin
    image: microbin-docker
    restart: always
    volumes:
      - ./microbin-data:/app/pasta_data

Any help greatly appreciated

**Comment by airdogvan** [comment]
Not sure I understand you question.
I'm not sure where the docker-compose pulls its image from, but I do what I always do in all my docker setups and for instance I can give you an example of a search engine (relatively simple docker-compose file):

version: '3.7'

services:

  searx:
    container_name: searx
    image: searx/searx:latest
    restart: always
    command: ${SEARX_COMMAND:-}
    volumes:
      - ./searx:/etc/searx:rw

And this (again like all my other more complex docker-compose) works fine.

For reference I git cloned your repository and am running in that directory.

**Comment by dimatx** [comment]
If you are relying on docker hub, the 'searx/searx' analog for microbin is 'danielszabo99/microbin'. Try that for your 'image'.
