### ISSUE TITLE
More syntax highlighting

### ISSUE THREAD

**Issue by Raithmir** [szabodanika/microbin#105]
It would be great to have highlighting for PowerShell.

**Comment by webtroter** [comment]
Linking a Reddit comment (chain) about adding more syntax highlighting
[By u/BitDaniYT, 2 mo. ago](https://www.reddit.com/r/selfhosted/comments/xpd0vi/comment/iq3w655/?utm_source=reddit&utm_medium=web2x&context=3)

> Pretty much anything that syntect supports can be added with literally 1 line of HTML code. Currently the dropdown only has the ones it has because I wanted to keep the dropdown short so you can find the most common syntaxes easily. I think a new command line argument for adding extra options would be a great and easy solution.

**Comment by webtroter** [comment]
So I tried to simply add Powershell to the dropdown, with what I believe are the correct values. but the syntax is not highlighted correctly.
https://github.com/szabodanika/microbin/commit/d5b9deeccd1feeab5662c169e958728826eff785
