### ISSUE TITLE
Stuck on Invalid login details after one wrong entry

### ISSUE THREAD

**Issue by laundmo** [szabodanika/microbin#109]
Just set this up, and wanted to password-protect my instance.

When i tried to log in, i typo'ed my password and not it doesn't let me retry and just says `Invalid login details.` on a otherwise blank page.

It seems the only way to get around this is by changing the password configured in microbin.

using the danielszabo99/microbin:latest image as of writing this

**Comment by szabodanika** [comment]
Hi there, I think this is mostly a browser issue but I'll look into whether something has been implemented incorrectly. You can also supply username and password in the url like this by the way: https://username:password@myserver.com/

**Comment by laundmo** [comment]
oh sorry, i should probably have added that my browser is firefox, and I'm using the Traefik reverse proxy (which shouldn't affect anything)
