### ISSUE TITLE
How do I add a hyperlink to the text in the footer?

### ISSUE THREAD

**Issue by RalstonLiu** [szabodanika/microbin#110]
I used docker to build microbin, and added "--footer-text" to the yaml file. I tried to use markdown syntax and html syntax, but microbin can't recognize the hyperlink. It's best if it opens in a new window, thanks!

**Comment by szabodanika** [comment]
Have you tried using html for this? Like `<a href="https://newpage.com" target="_blank">Click Here</a>`

**Comment by RalstonLiu** [comment]
Yes, I tried that and it still didn't work as expected :(

This is part of my docker-compose.yml file

![](https://img.laoda.de/i/2022/11/17/f4byfk-2.webp)

This is what it looks like at the end

![](https://img.laoda.de/i/2022/11/17/f4udj1-2.webp)

**Comment by albocc** [comment]
Microbin uses Askama for templating. From [their documentation](https://djc.github.io/askama/template_syntax.html#html-escaping):

> Askama by default escapes variables if it thinks it is rendering HTML content. It infers the escaping context from the extension of template filenames, escaping by default if the extension is one of `html`, `htm`, or `xml`. When specifying a template as `source` in an attribute, the ext attribute parameter must be used to specify a type. Additionally, you can specify an `escape` mode explicitly for your template by setting the escape attribute parameter value (to `none` or `html`).
>
> Askama escapes `<`, `>`, `&`, `"`, and `'`, according to the [OWASP escaping recommendations](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#output-encoding-for-html-contexts). Use the `safe` filter to prevent escaping for a single expression, or the `escape` (or `e`) filter to escape a single expression in an unescaped context.

The text you provided is not rendered as HTML due to this escaping. The solution would be to adjust the code in the `footer.html` template to trust the string like this:

```html
<p style="font-size: smaller">
    {% if args.footer_text.as_ref().is_none() %}
    <a href="https://microbin.eu">MicroBin</a> by Dániel Szabó and the FOSS Community.
    Let's keep the Web <b>compact</b>, <b>accessible</b> and <b>humane</b>!
    {%- else %}
    {{ args.footer_text.as_ref().unwrap() | safe }}
    {%- endif %}
</p>
```
