### ISSUE TITLE
404 error with curl

### ISSUE THREAD

**Issue by wilful** [szabodanika/microbin#113]
When i try post something in the console have a 404 error
My own host here
`curl -d "content=This is a test pasta" -X POST https://0ae.ru/create`

I launched in the container

```
$ nomad alloc exec -i -t -task 0ae 027f5a40 /bin/bash
root@c391aff5e1bd:/app# microbin --version
microbin 1.2.0
root@c391aff5e1bd:/app# 
```

Running args
```
        args = [
          "--highlightsyntax",
          "--private",
          "--qr",
          "--title=0ae.ru",
          "--no-file-upload",
          "--hide-footer",
          "--enable-burn-after",
          "--hash-ids",
          "--public-path=https://0ae.ru"
        ]
```

No logs in the container, how i can enable logging?

**Comment by luxus** [comment]
the url in the doc is wrong.. its upload. here is a py example
````python
def dropsecret(text, url="http://example.com/upload"):
    response = requests.post(url, files=dict(content=text), allow_redirects=False)
    return response.headers["Location"]
  ````

**Comment by wilful** [comment]
Thx for help! It is working

**Comment by szabodanika** [comment]
https://github.com/szabodanika/microbin.eu/commit/83138a776611eb4a702001c8eb50ec78d5cb5f06

For future reference, the doc and the entire website is also open-source: https://github.com/szabodanika/microbin.eu
