### ISSUE TITLE
Pasta is recorded wrongly

### ISSUE THREAD

**Issue by jchia** [szabodanika/microbin#114]
If you try to make a new pasta by pasting the following into the 'content' box:
```
1
2
--- a
3
```
you will get a pasta that does not have the lines before the `---`. After saving pasta and viewing it, you will see that the first 2 lines are replaced with a blank line:
```

--- a
3
```

The problem goes away if the line `--- a` is changed to `- a`.

**Comment by szabodanika** [comment]
Hi there, which version of MicroBin are you on? This seems like #88

**Comment by jchia** [comment]
I'm getting the problem on the latest master.

And, the problem actually is not as simple as I described. Simply creating a new pasta will not repro the problem. To repro the problem:

1. Create a new, editable, empty pasta.
2. Edit it, paste the problematic text, and save.
3. See that the part before the "---" turned into a blank line.

**Comment by jchia** [comment]
#115

**Comment by szabodanika** [comment]
#115 was merged, thanks @jchia! Sorry for taking long with it. Hopefully your issue will be solved now.
