### ISSUE TITLE
Crash when runs on non default port with error: "attempt to divide by zero"

### ISSUE THREAD

**Issue by CompuRoot** [szabodanika/microbin#118]
## To reproduce:

**Host:** debian amd64
**microbin:** microbin-v1.2.0-i686-unknown-linux-musl.tar.gz
**run:** `microbin -p 15155`
**Action:**       
- access microbin on `htttp://ip.ip.ip.ip:15155`
- type anything in **Content** textarea and hit **Save** button

**Fail:**      
- browser redirects to `htttp://ip.ip.ip.ip:15155/upload` and end up with error: "This site can’t be reached. The connection was reset."
- Error log in console where `microbin` is running:
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'attempt to divide by zero', src/util/animalnumbers.rs:20:21
```

**Comment by goldstar611** [comment]
I think this is a duplicate of #107 Looks like the 32 bit version is being used here.

**Comment by CompuRoot** [comment]
> I think this is a duplicate of #107 Looks like the 32 bit version is being used here.

You are absolutely right, target machine hasn't  supports for 32 bits binaries.  Matched x86_64 binary works as expected.   
Sorry for the noise and thank you for the `microbin`!
