### ISSUE TITLE
Data loss after updating the docker container

### ISSUE THREAD

**Issue by AuthorShin** [szabodanika/microbin#119]
Hello
I just updated my MicroBin container to the latest version and after that I saw that all my pastas are gone and the list is empty.

**Comment by jchia** [comment]
Do you have a backup of the data? Have you tried downgrading the container?

**Comment by AuthorShin** [comment]
@jchia I had a backup that saved me but `database.json` was empty after the upgrade.

**Comment by AuthorShin** [comment]
I'll try to provide that.

**Comment by diamondsw** [comment]
Was database.json on a persistent volume? Important to know if the upgrade was at fault or if it's a Docker configuration issue.

**Comment by AuthorShin** [comment]
It was on a persistent volume.

**Comment by szabodanika** [comment]
On the newest few versions this doesn't seem to be an issue anymore (for me), even across different beta versions of v2, so I will close it. Feel free to reopen it if anyone else experiences data loss after updates.
