### ISSUE TITLE
Being able to add Command Line Arguments as Environment Variables for docker version

### ISSUE THREAD

**Issue by AuthorShin** [szabodanika/microbin#122]
Hello
That would be very great and super easy for everyone if you consider adding an option to be able to add Command Line Arguments as Environment Variables for docker version.

**Comment by PerchunPak** [comment]
It's already implemented. You can use `MICROBIN_BIND=0.0.0.0` for `--bind 0.0.0.0` or `MICROBIN_PRIVATE=true` for `--private`.

**Comment by AuthorShin** [comment]
@PerchunPak Thank you for the answer, where can I find the full list/guide?

**Comment by PerchunPak** [comment]
Just look at text in brackets in [docs](https://microbin.eu/documentation/#command-line-arguments). And do not forget append to every key `MICROBIN_` prefix, so if you see `AUTH_USERNAME` actual environment variable would be `MICROBIN_AUTH_USERNAME=some_value`.

**Comment by AuthorShin** [comment]
Thanks a lot mate, highly appreciated.

**Comment by PerchunPak** [comment]
NP, please close this, as it seems like resolved.

**Comment by timdonovanuk** [comment]
Might want to update the URL here, as it's broken. And the document does not make it clear that the command line arguments are not what is documented:

https://microbin.eu/docs/installation-and-configuration/configuration

MICROBIN_BASIC_AUTH_USERNAME is actually --basic_auth_username etc.
