### ISSUE TITLE
[feature request] when uploading over curl, is it possible to issue a response with the URL of the paste?

### ISSUE THREAD

**Issue by ldpr** [szabodanika/microbin#134]
For example, if I have /pastalist disabled there's no list of pastes. If I were to upload a paste using curl there's no response, but the paste does get made. There's no way for me to find and use it though lol.

Ideally, I'd get returned the URL as a response from the curl which I can then use & share.

Thanks for your time - microbin looks very promising!

**Comment by bdelwood** [comment]
`curl` can do this directly by having it print the redirect URL. For example:

```bash
curl -F expiration=1min -F content="This is a test." -X POST -w '%{redirect_url}\n' https://microbin.example.com
```

**Comment by ldpr** [comment]
> `curl` can do this directly by having it print the redirect URL. For example:
> 
> ```shell
> curl -F expiration=1min -F content="This is a test." -X POST -w '%{redirect_url}\n' https://microbin.example.com
> ```

Very clever solution! I'm not sure, should I close this or do you think it should (could?) be handled by microbin also?

**Comment by ldpr** [comment]
closing this, it's silly and i didn't really think it through at all. also @bdelwood nailed the answer - thanks again :)
