### ISSUE TITLE
Custom URL

### ISSUE THREAD

**Issue by Endo-Heikichi** [szabodanika/microbin#136]
Firstly, thank you for the amazing project.

Just wished to confirm whether it is possible to implement Custom URLs as seen in Rentry (https://github.com/radude/rentry). 

If this feature is currently not possible, then I hope you consider it. It seems like a neat enhancement considering you have a built-in URL shortener.

**Comment by szabodanika** [comment]
Duplicate (#83) but good idea, I would like to add this!
