### ISSUE TITLE
Version number not updated (after updating to 1.2.1)

### ISSUE THREAD

**Issue by Panja0** [szabodanika/microbin#149]
Just updated my Docker install to the latest Docker image.
When I go to the info tab I still have:
<img width="178" alt="Screenshot - 2023-03-27 at 11 39 04" src="https://user-images.githubusercontent.com/12939350/227904164-f9198b9a-38d1-4c34-b146-295ff3e1c3a1.png">

**Comment by szabodanika** [comment]
I forgot to update it there, sorry about that and thanks for the issue. 1.2.2 will add a few tiny features again in a week or so, I will update the versioning properly.
