### ISSUE TITLE
CSS not found after updating to 1.2.1

### ISSUE THREAD

**Issue by Chickensoupwithrice** [szabodanika/microbin#160]
Hey there, the /water.css (as well as favicon and logo) now returns 404 since I updated to version 1.2.1 (was previously on 1.1.0) 

Here's a screenshot as proof

My bin is running on https://bin.sealight.xyz

Previously when running 1.1.0 I had no trouble loading up `water.css` or any of the other files (logo, favicon) not sure what's happened?

![image](https://github.com/szabodanika/microbin/assets/22575913/4029c739-31ce-452f-8788-bdcf3b12e077)

**Comment by szabodanika** [comment]
Hi, can you share what parameters you set on microbin? To me it seems like you specified a public path but used only domain name without the protocol. Try setting `https://bin.sealight.xyz` instead of `bin.sealight.xyz`.

**Comment by Chickensoupwithrice** [comment]
Ahhh, yeah that fixed it! I think previous versions may not have required this? Or at least the docs that came bundled with my old installation of microbin didn't seem to specify that the protocol was also necessary. 

Thank you for your work on microbin and your quick response! :)
