### ISSUE TITLE
Session seems to hang at end of upload?

### ISSUE THREAD

**Issue by mcdent** [szabodanika/microbin#199]
I've set microbin up with Cloudflare reverse proxy/zero trust.
I set the `MICROBIN_PUBLIC_PATH` to the external facing domain.
When uploading a file, the session appears to hang and not complete.
However if you navigate to the `list` the file/text is actually there.

**Comment by szabodanika** [comment]
How long does it hang and what size is the file? When it reaches 100% it is normal to hang a bit as the percentage only measures the file transmission to the server, but the redirection only happens once the upload has been fully processed by the server. If it hangs for a long time with a small file, that could indicate that your server is having trouble writing to the disk for some reason

**Comment by mcdent** [comment]
Ok, well its the redirection that is not happening when I access via cloudflare. 
The file does seem to  upload but you are just left with a no entry sign over the upload button. 
However if you click on the list button, the file is actually there.
If I then change the env file setting `MICROBIN_PUBLIC_PATH` and set it to my local IP:port everything works as normal/expected.
Thanks

**Comment by mcdent** [comment]
Ok, seems I sorted it. When I specificed my public URL , I omitted the `s` from `https` .
Looking good now. The aspect ratio of an uploaded images is sometimes incorrect in the preview though.
