### ISSUE TITLE
URL Shortening does not work

### ISSUE THREAD

**Issue by Y0ngg4n** [szabodanika/microbin#20]
If i short an URL by just simply pasting only the URL in my Pasta and opening it on a other device i just get the normal text and dont get redirected to the URL.

**Comment by szabodanika** [comment]
Welcome @Y0ngg4n and thanks for using MicroBin. 
After saving your URL as a paste, how did you try to open it? 
`https://yourserver.com/url/fish-deer-viper` should behave as a URL redirect while
`https://yourserver.com/pasta/fish-deer-viper` will show the URL as text. When saving your URL, it will redirect you to the pasta endpoint to prevent you from getting instantly redirected to your URL.

**Comment by szabodanika** [comment]
I agree with you, this should be clarified either in the readme or somewhere on the UI.
