### ISSUE TITLE
Add image on dockerhub

### ISSUE THREAD

**Issue by Y0ngg4n** [szabodanika/microbin#23]
Please add a image on dockerhub or github registry. For a kubernetes Setup it is really not that easy to deploy it without creating a ci pipeline.

**Comment by AuthorShin** [comment]
@szabodanika Hello, any update on this?

**Comment by Y0ngg4n** [comment]
@AuthorShin does not seem so

**Comment by Schnuecks** [comment]
@szabodanika Any progress on that?

**Comment by arghyadipchak** [comment]
Images for arm64 and amd64 are now available on [DockerHub](https://hub.docker.com/r/danielszabo99/microbin) after merge #49

**Comment by szabodanika** [comment]
I will continue to monitor this thread and if anyone encounters any issues with the new DockerHub images I will try to get a fix asap. 🙂

**Comment by Schnuecks** [comment]
container works normal but the healthchecks fail so the container gets unhealthy 
/bin/sh: 1: curl: not found

**Comment by szabodanika** [comment]
Would this fix the issue?

https://github.com/fescobar/allure-docker-service-ui/commit/f71719a4c7737a10dd87898cfecab963f6644499

**Comment by arghyadipchak** [comment]
> Would this fix the issue?
> 
> [fescobar/allure-docker-service-ui@f71719a](https://github.com/fescobar/allure-docker-service-ui/commit/f71719a4c7737a10dd87898cfecab963f6644499)

It should. Also how about adding healthcheck to docker image by default?

**Comment by Schnuecks** [comment]
I think it's nice to have, but with curl comes all the backdraws security image sizes etc. I would prefer something like this https://medium.com/bash-tips-and-tricks/part01-tcp-udp-request-with-a-native-bash-feature-and-without-curl-wget-9dcef59c30aa

**Comment by arghyadipchak** [comment]
> I think it's nice to have, but with curl comes all the backdraws security image sizes etc. I would prefer something like this https://medium.com/bash-tips-and-tricks/part01-tcp-udp-request-with-a-native-bash-feature-and-without-curl-wget-9dcef59c30aa

That's a good idea. Will look into it.
