### ISSUE TITLE
Looking forward to adding the function of QR code scanning and sharing

### ISSUE THREAD

**Issue by sunteta** [szabodanika/microbin#242]
I have to admit that MicroBin is very easy to use, but the mobile phone is used too frequently. If two unfamiliar mobile phones communicate with each other, it is not possible to obtain the shared URL. Every time I enter the URL in the browser, it is too difficult to input on the mobile phone. Longer.

If you add the function of QR code, it is really important to use mobile phone scanning to quickly open the web page and obtain the shared content.

I am looking forward to adding the QR code sharing function.

**Comment by DX37** [comment]
It enables, when in config, like `.env`, you set this variable, which is, as config comment tells, required for QR to work:
```
export MICROBIN_PUBLIC_PATH=<your public site URL>
```
and obviously:
```
export MICROBIN_QR=true
```
It's all in `.env`, at least.

**Comment by szabodanika** [comment]
Thank you DX37, like you explained this feature already exists.
