### ISSUE TITLE
How to pass command line args as env var in docker-compose file?

### ISSUE THREAD

**Issue by amnesiacsardine** [szabodanika/microbin#25]
As the title says. If it is not implemented yet, how else can I change the default behavior?

**Comment by szabodanika** [comment]
Hello @amnesiacsardine and welcome! Thanks for raising this issue. I must admit I am not a big Docker expert and I have pretty much no experience in properly dockerising services. I agree with your suggestion though and will look into it. As always, PRs are also very welcome if you happen to know how to solve this. 😃  For now, anyone facing the same issue will definitely find your comment above helpful.

**Comment by uniqueNullptr2** [comment]
as an additional reference to amnesiacsardine: you can override the command from the docker-compose as well. no need to rewrite the dockerfile.
