### ISSUE TITLE
[enhancement request]: show pasta name on the main page in addition to url

### ISSUE THREAD

**Issue by binuengoor** [szabodanika/microbin#36]
Currently the newly created pasta name only shows up within the url. For people using the service on  mobile devices, it might not be easy to view. Hence it would be good to add pasta name to the main page once its created.

**Comment by szabodanika** [comment]
I like this idea a lot, I always wanted to add a field somewhere on the pasta page with the URL that would be easier to copy. Would you rather have the entire URL or just the animal names displayed?

**Comment by binuengoor** [comment]
I think what would be nice is to display the pasta name once created, along with an option to copy the full url. Please see the attached picture to see what I mean.

![pasta](https://user-images.githubusercontent.com/62013964/180785999-2010319a-972c-4488-8855-fa60809c759d.png)

**Comment by szabodanika** [comment]
I love the "your pasta is ready" message 😁 This all looks great to me, although I'm not sure if we can implement the click to copy function without JS. Currently MicroBin has 0 lines of JS and I hoped to keep it that way, but perhaps we can sneak in 2-3 lines for this feature.

**Comment by binuengoor** [comment]
Sure. You can also start with url or just the pasta and then add JS code in the future if there is a strong need. Will give you time to do research.

On another note, I feel the name of the application could be better. MicroBin, while it speaks to the nature of the application, does not have that fun-element. The implementation of animal names is really clever.

I feel you could have named the app for those animal stuff or the pasta element. Some keywords to relate include, animal, zoo, pasta, etc.
"PastaBin" is an obvious quick choice. Just throwing out some ideas. Food for thought.

I feel its a fantastic application with a lot of use cases as is. Key is to keep it simple and stable always. Too many features also comes in the way to usability. Cheers.

**Comment by szabodanika** [comment]
I think at this point the name has to stay but you're more than welcome to make a fork with a different name (it is BSD 3 licensed after all). I agree with the "fun element" missing though, what I was playing around is a new icon insted of a plain black mju character. I think I even have a branch for that rebranding. But anyway, probably should move this discussion over to #40
