### ISSUE TITLE
How to use --footer_text or --title?

### ISSUE THREAD

**Issue by binuengoor** [szabodanika/microbin#37]
I cannot seem to figure out how to pass a string to these arguments.

For context, I am trying to pass these arguments in the docker compose like so:
    command: ["microbin", "--highlightsyntax", "--editable", "--hide-footer", **"--title 'newtitle**'"]

Tried different combinations such as 
title:'new'
title new
title 'new'

nothing seem to be working. I have a feeling I am doing something dumb. Appreciate your help.

**Comment by uniqueNullptr2** [comment]
["microbin", "--highlightsyntax", "--editable", "--hide-footer", "--title", "newtitle"]
should be like this.

However, there seems to be a logic error preventing the new title from being used, and passing in footer-text causes an Unwrap on a None value somehow. Can you reproduce that?

**Comment by binuengoor** [comment]
> Can you reproduce that?

yes. It is completely ignoring the new title set via the command. everything else works.

**Comment by szabodanika** [comment]
As @uniqueNullptr2 pointed out in the discussion of #34, templates/header.html:4 checks whether footer text is set to decide whether the title text should be changed. As a workaround now you can set a footer text to enable the title change until this is fixed. You're very welcome to open PR for this fix as well!
