### ISSUE TITLE
[Feature Request] Add MicroBin to the Unraid Community Apps.

### ISSUE THREAD

**Issue by moritz-john** [szabodanika/microbin#48]
My feature request is a very easy to install version of MicroBin on the [Unraid Community Apps](https://unraid.net/community/apps).

I tried to do it myself but I have very little knowledge with Docker, Docker Hub or how to officially add an app to the Unraid CA:

![2022-08-15_11-50](https://user-images.githubusercontent.com/70295002/184615181-3969df0b-6a91-412a-843a-92f9765c50b2.png)

I clicked on `ADD CONTAINER` in the Unraid docker GUI and added the following:
Name: `microbin`
Repository: `solarft/microbin`

I added a new port:
WebUI: 
Container Port: `8080`
Host Port: e.g. `7123`

I added a new path:
Data Path:
Container Path: `/usr/local/bin/pasta_data`
Host Path: `/mnt/user/appdata/microbin/data/`

**As you can tell from the screenshot, basic functionality works and I can access, create and save new pasta in my local network.**

___

**I don't know if `solarft/microbin` is the official MicroBin docker hub repository**, there were about 4 different ones and I tried them until one worked.

Also I have no idea how to pass command line arguments like `--highlightsyntax`. I tried many things but none of them worked.

___

I've done what I can and failed, maybe someone else is able to fulfill this feature request.

Thank you!

**Comment by szabodanika** [comment]
We have a new official DockerHub image (see #49). Personally I have not used Unraid Community Apps before but I will have a look if I can make the worfklow easier. You can also give it another try, maybe the command line arguments work now with the changed Dockerfile. Otherwise I will have a look as I really want to get the arguments working on Docker.

**Comment by abyss** [comment]
Microbin is in Unraid Community Apps under Joshdroids Repository - using the official dockerhub image, as well. His Unraid support thread is here: https://forums.unraid.net/topic/112086-support-joshndroids-docker-repo-support-thread/ - and you can easily find it in CA by searching microbin. I'm currently using it in my environment successfully.

The only way to use arguments with Docker is to make them environment variables (the standard pattern), or modify the Dockerfile (which means building your own image and making it available for use). Thankfully, https://github.com/szabodanika/microbin/pull/34 has made all (most?) of the options env vars, and this works perfectly fine for me with the current image! 

All that is currently missing is some basic documentation of the options, but the general idea is:
> Naming of the environment variable is "MICROBIN_" + the name of the option in all caps.

@moritz-john or @szabodanika I think you can close this issue as resolved :)

**Comment by moritz-john** [comment]
![image](https://user-images.githubusercontent.com/70295002/196106434-ae50b783-93df-4f03-a56d-95ef4e3d8275.png)

So it got added Sep 30, 2022 to the Unraid CA. Nice :)

@abyss Thank you for pointing that out - I had not checked since creating my feature request on Aug 15, 2022.
Also thank you for your small tutorial on how to add environment variable to MicroBin in Unraid.

@szabodanika Thank you for updating me some days ago.

I'd also consider this "issue" resolved/closed.

**Comment by szabodanika** [comment]
@szabodanika note to self: add a mention of this to README.MD
