### ISSUE TITLE
[Feature request] option to use random characters instead of animal names

### ISSUE THREAD

**Issue by Ember-ruby** [szabodanika/microbin#54]
not a major issue, but for just sharing links (over copy/paste) I'd rather it be as short as possible, as the animal names can get pretty long for their relative low density of information

**Comment by Panja0** [comment]
I can relate to this as well.
So +1

**Comment by henry40408** [comment]
hi @szabodanika I'd like to claim this issue. I'd like to...

- Use [hashids](https://hashids.org/rust/) since we need to serialize primary key to animal names and vice versa
- Add a new option `--hashids` for user this feature and let animal names be the default

**Comment by szabodanika** [comment]
Seems like a good option to have and @henry40408 I am happy with you creating a PR for this, including using that library if it makes the URLs significantly shorter. The name for the new arg could be `--hash-ids` just to match the pattern we have with the rest.

I think the following would be the simplest way to implement this, but feel free to be more creative:

1. create a second coverter `hash_ids` with hashids library with 2 functions `to_u64` and `to_hash` in the same style as `animalnumbers.rs`
2. create a third converter (e.g. `id_converter`) that also has 2 functions and calls either animalnumbers or the second converter based on the presence of the `--hash-ids` arg
3. call this third converter everywhere where `animalnumbers::to_u64` or `animalnumbers::to_animal_names` is called currently
4. profit

I don't see us adding more numbering schemes in the future but if we want emoji-based ID's or whatever, it should be fairly simple to add it following this pattern

**Comment by henry40408** [comment]
@szabodanika I have submitted a pull request. Please help review thanks.
