### ISSUE TITLE
Docker volume not correct?

### ISSUE THREAD

**Issue by Panja0** [szabodanika/microbin#55]
I just created a Docker container on my Synoloy NAS and used:
```
    volumes:
     - ./microbin-data:/usr/local/bin/pasta_data
```

But after examining the container itself I noticed the folder should be:
`/app/pasta_data`

Or at least `/usr/local/bin/pasta_data` is empty for me and `/app/pasta_data` has the database.json file etc.

**Comment by szabodanika** [comment]
Are you referring to the instructions in https://github.com/szabodanika/microbin#docker? I suppose that should be updated to the following then? This path changed with 08871e15b651a37774ea62802ab236cdf73bc11e. 
```
    volumes:
     - ./microbin-data:/app/pasta_data
```

**Comment by Panja0** [comment]
Correct!

**Comment by szabodanika** [comment]
Thanks a lot, nice catch!

**Comment by Panja0** [comment]
No worries mate! Thanks for creating this awesome piece of software!
