### ISSUE TITLE
Command Line Argument -V, --version not working in Docker

### ISSUE THREAD

**Issue by Panja0** [szabodanika/microbin#56]
When using the following CLI argument `-V` or `--version` in docker the container won't (re)start.
It keeps starting and than stops.

Other arguments like `--hide-footer` and `--private` do work.

**Comment by szabodanika** [comment]
The version argument simply prints the version of microbin (e.g. v1.1.1) and exits, so I would say this is expected behaviour in Docker. What were you attempting to use it for?

**Comment by Panja0** [comment]
Ahhh ok! Did not understood correctly than.
I though it would add a version mark somewhere on the site.

**Comment by szabodanika** [comment]
No worries. I will consider rewording the description in the documentation about this.
