### ISSUE TITLE
[Feature request] Default expiration time changable

### ISSUE THREAD

**Issue by Panja0** [szabodanika/microbin#61]
Would be great if we could set the default expiration time ourselves. 
By default it's set to 24 hours. But for instance I would like to set the default to 1 min.

**Comment by pluja** [comment]
It would also be great to have an option to disable the "Never" expire option so all the pastas expire

**Comment by szabodanika** [comment]
Both will be fairly simple to implement, should someone want to jump on either, or both in a single PR. I will target this for 1.2.0.
