### ISSUE TITLE
Is there a way to start microbin as windows service

### ISSUE THREAD

**Issue by ket000** [szabodanika/microbin#77]
When I reboot the machine, I have to manually start microbin. Like linux, can we have a way to start microbin automatically on reboot using windows service.

**Comment by abyss** [comment]
There's not native functionality in the application, but you can either add it to automatic startup in Windows, or use something like "NSSM" to create a service wrapper around it. Which you choose depends whether you care about it specifically being a service, or if you just want it to automatically start.

This is true of Linux as well, just the provided example is using systemd as the service manager/wrapper. :)

**Comment by ket000** [comment]
Thanks. I just added it to startup folder for easy management. nssm link is here : https://nssm.cc/download

However I see this project is not maintained so I would stick with startup option for now. Hopefully some day rust will support windows or linux services natively thru add on crate. In future once systemd service is available for regular windows build using wsl, I may use that. For now startup folder option is working fine.

**Comment by ket000** [comment]
https://crates.io/crates/windows-service/0.1.0 can be used for creating windows service. May be some one will document steps to enable microbin as native windows service.
