### ISSUE TITLE
[Feature Request] Link to URL Redirect URL on Redirect Pastas

### ISSUE THREAD

**Issue by abyss** [szabodanika/microbin#80]
Right now, if you create a URL redirection pasta, and you don't copy the link from the pastalist, there's no obvious way to use the redirect feature.

I propose adding a read-only text box with the /url/ endpoint in a copyable format, perhaps to the right of the Remove button or between the Raw/Remove buttons and the content. Then when redirected to the /pasta/ endpoint when creating it, you will be able to copy the /url/ endpoint to send off. :)

**Comment by szabodanika** [comment]
I think this can be implemented by pretty much copying code from #70 (after my suggestions) and adding the Copy button on the right side with the rest of the action buttons on the page

**Comment by szabodanika** [comment]
@abyss I added a copy button on my personal branch, would you please have a look and let me know if you like it before I merge it to master?
