### ISSUE TITLE
Long pastas are inconsistently saved

### ISSUE THREAD

**Issue by Ember-ruby** [szabodanika/microbin#81]
any pastas longer than a few K characters are inconsistently saved, sometimes they'll be cut off to a much shorter length, sometimes it'll save correctly, nothing appears wrong in microbins logs and there are no other issues (~~apart from the copy button also failing on long pastas~~ nevermind, that just seems to be broken)

**Comment by szabodanika** [comment]
Can you please show us the text that you tried to save and the text that was saved?

**Comment by Ember-Ember** [comment]
so, example, copying the GPL lisence as example text, 1 copy works fine, same with two, but three is cut-off in this way 
[gpl-example.txt](https://github.com/szabodanika/microbin/files/9847311/gpl-example.txt)

**Comment by szabodanika** [comment]
I was able to reproduce this a few days ago with the GPL text and with random characters but both https://raw.githubusercontent.com/QuiltMC/cozy-discord/root/yaml-files/welcome-community.yaml and 20K random character string work absolutely fine for me today.

**Comment by Ember-ruby** [comment]
can't seem to recreate in 1.2.0

**Comment by laundmo** [comment]
i was able to recreate in 1.2.0-20221107 

it seems to save only partially when scrolled down and the mouse cursor is placed at the bottom. when i place the cursor at the top it saves properly.

**Comment by szabodanika** [comment]
> i was able to recreate in 1.2.0-20221107
> 
> it seems to save only partially when scrolled down and the mouse cursor is placed at the bottom. when i place the cursor at the top it saves properly.

This is hilariously random. Can you say whether your browser is sending the whole text to the server? Just want to narrow down whether this is a browser or server side issue

**Comment by szabodanika** [comment]
With v2.0.3-beta4 I am able to save 12 copies (8000 lines) of GPL3 license with no issues other than my browser struggling to render all the text. I think this issue has been solved but please do let me know if anyone still experiences it with v2
