### ISSUE TITLE
docker build action failed

### ISSUE THREAD

**Issue by Schnuecks** [szabodanika/microbin#82]
something went wrong on building the docker image. could someone check. thanks.

**Comment by szabodanika** [comment]
I cancelled the action after the last commits I made because it's configured to only push the images with new tags anyway, but I forgot to delete the cancelled ("failed") runs. I did a test run later and it works absolutely fine. :-)

**Comment by Schnuecks** [comment]
when will you push the latest on docker, the last published on docker is from a month ago?

**Comment by szabodanika** [comment]
v1.2.0 will be the next one, there's a few more issues and PRs that need to be sorted out. I hope to do this within the next week or so
