### ISSUE TITLE
(Feature) Self-destruction after set amount of views

### ISSUE THREAD

**Issue by luxus** [szabodanika/microbin#84]
I didn't see any information about it in the readme, i would like to have the option. that notes get self-destroyed after a amount of times it got opened

**Comment by szabodanika** [comment]
I almost implemented this at one point but for some reason I discarded the idea. I think this is a very useful feature and should be easy enough to add. Won't target this for 1.2.0 but I want this in the release after

**Comment by luxus** [comment]
A dropdown with Amount of times it can be opened infinite,1,3,5 but a checkmark would fine too :D

**Comment by luxus** [comment]
@szabodanika thanks for implementing it so fast 👍🏼 
are options private & self-destruction and avail. from curl?
