### ISSUE TITLE
material icon to mark text to copy and a icon for the link

### ISSUE THREAD

**Issue by luxus** [szabodanika/microbin#92]
i think the ux could benefit from icons
https://pictogrammers.github.io/@mdi/font/6.9.96/
next to the link a mdi-web ( globe )
next to the text field a mdi-clipboard-file

**Comment by szabodanika** [comment]
Having a lot of feature-creep for the next version, so I will close this as wontfix for now. A custom CSS however can be set for MicroBin, and that stylesheet can add icons or modify the buttons and links in any way. I hope one day we will have a bunch of custom styles for MicroBin in a library.
