### ISSUE TITLE
Latest image disappeared from docker

### ISSUE THREAD

**Issue by mariushosting** [szabodanika/microbin#93]
docker: Error response from daemon: manifest for danielszabo99/microbin:latest not found: manifest unknown: manifest unknown.

**Comment by szabodanika** [comment]
Hi there, I'm having issues with our docker image build, but I am trying to sort dockerhub out asap. :-)

**Comment by Joshndroid** [comment]
Yep i can confirm on unraid through docker i am seeing the same thing.
It is as if the 'latest' tag is now gone... if i manually change to 1.1.1 it seem to like that and doesn't error out.
My other docker containers are working as expected so doesn't seem to be a docker wide issue to me at least.

**Comment by szabodanika** [comment]
I think I managed to fix the issue, the automated build is running now on GH Actions, let's hope it goes well

**Comment by szabodanika** [comment]
Seems to be all good now! Last thing to do for the 1.2.0 release is to update the documentation on the website 😊

**Comment by Joshndroid** [comment]
Thanks @szabodanika ... its back and working as expected :)
