### ISSUE TITLE
Docker image for arm64 Raspberry Pi?

### ISSUE THREAD

**Issue by mmozzano** [szabodanika/microbin#96]
Hi there,

Looks like a great project -any plans for providing a docker image for arm64 pi?

Thanks

**Comment by szabodanika** [comment]
Hi there, the current docker image on dockerhub works on the arm64 raspberry pi, does it not? It should be in theory but I havent deployed the latest image on my Pi4 yet. See https://github.com/szabodanika/microbin/blob/76cfc906ef0c75e551e2995810a521c5fa503ef5/.github/workflows/docker.yml#L42 and https://hub.docker.com/layers/danielszabo99/microbin/latest/images/sha256-b0b9f5974fa56af40cb848cb74d131960f1514b11d2a0467f01000d79cb29671?context=explore

**Comment by mmozzano** [comment]
Sorry yes, my mistake!  I looked at the tags but didnt see the arm64 tag, thought I only saw amd64.  

Thats what I get for trying to do stuff before morning coffee 😄
